name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

#
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci
      - run: npm run setup
      - run: npm test
      - run: npm run build

      - name: Get package version
        if: failure()
        id: get_package_version
        run: echo ::set-output name=package_version::$(node -p "require('./package.json').version")

      - name: Upload artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: dist-${{ steps.get_package_version.outputs.package_version }}-${{ matrix.node-version }}
          path: dist
