import assert from "node:assert/strict"
import fs from "fs"
import { noop } from "lodash"
import MiniCssExtractPlugin from "mini-css-extract-plugin"
import path from "path"
import postcssPresetEnv from "postcss-preset-env"
import webpack from "webpack"
import BaseWebpackDevServer from "webpack-dev-server"
import { merge } from "webpack-merge"

const UPDATE_SNAPSHOTS = process.env.UPDATE_SNAPSHOTS === "1"

function assertSnapshot(content: string, snapshotFile: string) {
  if (UPDATE_SNAPSHOTS || !fs.existsSync(snapshotFile)) {
    fs.mkdirSync(path.dirname(snapshotFile), { recursive: true })
    fs.writeFileSync(snapshotFile, content, "utf-8")
    return
  }

  const expected = fs.readFileSync(snapshotFile, "utf-8")
  assert.equal(content, expected, `Snapshot mismatch: ${snapshotFile}`)
}

export async function testBuild(config: webpack.Configuration, snapshotDir: string) {
  config = {
    ...config,
    mode: "production",
  }

  const compiler = webpack(config)
  const stats = await compilerRun(compiler)

  // Test the user script file (*.user.js) generated by the compilation
  const files = stats.chunks!.flatMap((chunk) => chunk.files)
  assert.equal(files.length, 1, `Expected 1 output file, got ${files.length}`)
  const content = fs.readFileSync(`${config.output!.path}/${files[0]}`, "utf-8")
  assertSnapshot(content, path.join(snapshotDir, "build-1.txt"))

  // Test the meta file (*.meta.js) generated by the compilation
  const auxiliaryFiles = stats.chunks!.flatMap((chunk) => chunk.auxiliaryFiles)
  assert.equal(auxiliaryFiles.length, 1, `Expected 1 auxiliary file, got ${auxiliaryFiles.length}`)
  const auxiliaryContent = fs.readFileSync(`${config.output!.path}/${auxiliaryFiles[0]}`, "utf-8")
  assertSnapshot(auxiliaryContent, path.join(snapshotDir, "build-2.txt"))
}

function compilerRun(compiler: webpack.Compiler) {
  return new Promise<webpack.StatsCompilation>((resolve, reject) => {
    compiler.run((err, stats) => {
      if (err) {
        if ((err as any).details) {
          err.message = `${err.message} (${(err as any).details})`
        }

        return reject(err)
      }

      if (!stats) {
        return reject(new Error("No stats"))
      }

      const info = stats.toJson()

      if (stats.hasErrors()) {
        return reject(new Error(info.errors?.map((e) => e.message).join("\n\n")))
      }

      if (stats.hasWarnings()) {
        console.warn(info.warnings)
      }

      compilerClose(compiler)
        .then(() => resolve(info))
        .catch(reject)
    })
  })
}

function compilerClose(compiler: webpack.Compiler) {
  return new Promise<void>((resolve, reject) => {
    compiler.close((err) => (err ? reject(err) : resolve()))
  })
}

export interface UseDevServerOptions extends webpack.Configuration {
  noCompile?: boolean
}

export interface UseDevServerContext {
  server: WebpackDevServer
  origin: string
}

export async function useDevServer(
  { noCompile, ...config }: UseDevServerOptions,
  fn: (context: UseDevServerContext) => Promise<void>,
) {
  config = merge({}, config, {
    mode: "development",
    devServer: {
      host: config.devServer?.host || "127.0.0.1",
      port: config.devServer?.port || (await getFreePort()),
    },
  })

  if (noCompile) {
    config = merge({}, config, {
      devServer: {
        hot: false,
      },
    })
  }

  const compiler = webpack(config)

  if (noCompile) {
    preventCompilation(compiler)
  }

  const server = new WebpackDevServer(config.devServer, compiler)

  try {
    await server.start().catch((e) => {
      if (!(e instanceof CompilationPrevention)) {
        throw e
      }
    })

    const port = +(server.options.port || NaN)
    const host = server.options.host || "127.0.0.1"

    if (isNaN(port)) {
      throw new Error(`Invalid port: ${server.options.port}`)
    }

    await fn({
      server,
      origin: `http://${host}:${port}`,
    })
  } finally {
    await compilerClose(compiler)
    await server.stop().catch(console.warn)
  }
}

class CompilationPrevention extends Error {
  constructor() {
    super("compilation prevented as expected.")
    this.stack = undefined
  }
}

function preventCompilation(compiler: webpack.Compiler) {
  const flag = "__preventCompilation__"

  if ((compiler.compile as any)[flag]) {
    return
  }

  compiler.compile = (callback) => {
    callback(new CompilationPrevention())
  }
  ;(compiler.compile as any)[flag] = true
}

export function withCommonConfig(...config: webpack.Configuration[]) {
  const defaultConfig: webpack.Configuration = {
    resolve: {
      extensions: [".ts", ".js"],
      alias: {
        "@": path.resolve(__dirname, "../../src"),
      },
    },
    module: {
      rules: [
        {
          resourceQuery: /raw/,
          type: "asset/source",
        },
        {
          test: /\.([cm]?ts|tsx)$/,
          exclude: /node_modules/,
          use: {
            loader: "ts-loader",
            options: {
              transpileOnly: true,
            },
          },
        },
      ],
    },
    output: {
      clean: true,
    },
    devtool: false,
    watch: false,
    stats: "errors-warnings",
  }
  return merge({}, defaultConfig, ...config)
}

const commonCssRule = {
  test: /\.css$/i,
  use: [
    {
      loader: "css-loader",
      options: {
        modules: {
          auto: true,
          namedExport: false,
          localIdentName: "[name]__[local]--[hash:base64:4]",
        },
      },
    },
    {
      loader: "postcss-loader",
      options: {
        postcssOptions: {
          plugins: [postcssPresetEnv()],
        },
      },
    },
  ],
}

export function withMiniCssExtract(config?: webpack.Configuration): webpack.Configuration {
  const overrides = {
    plugins: [new MiniCssExtractPlugin()],
    module: {
      rules: [
        {
          ...commonCssRule,
          use: [MiniCssExtractPlugin.loader, ...commonCssRule.use],
        },
      ],
    },
  }
  return config ? merge({}, config, overrides) : overrides
}

class WebpackDevServer extends BaseWebpackDevServer {
  rejectStart: (err: unknown) => void = noop

  constructor(...args: ConstructorParameters<typeof BaseWebpackDevServer>) {
    super(...args)

    this["createServer"] = async function (...args: any[]) {
      const result = await BaseWebpackDevServer.prototype["createServer"].apply(this, args)

      this.server!.on("error", (err: unknown) => {
        this.rejectStart(err)
      })

      return result
    }
  }

  override async start() {
    return new Promise<void>((resolve, reject) => {
      this.rejectStart = reject
      super.start().then(resolve, reject)
    })
  }
}

export async function getFreePort(): Promise<number> {
  const port = await BaseWebpackDevServer.getFreePort("auto", "127.0.0.1")
  if (isNaN(+port)) throw new Error(`Received invalid port: ${port}`)
  return +port
}
